### ISSUE TITLE
Multiple DbContext

### ISSUE THREAD

**Issue by maka-dev** [ExtCore/ExtCore-Docs#1]
Hello, 

I am interested in using ExtCore and wanted to know, if it is possible to use mutlible DbContexts - like for each Plugin one DbContext but all using the same DB?
Intrested in covering the DDD pattern with your plug-in tech.

**Comment by DmitrySikorsky** [comment]
Hi! Yes, it is possible, and as I remember it is already implemented, please search on GitHub, I will share the link if find it.
